apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: wanderlust
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongo-service.wanderlust.svc.cluster.local:27017/wanderlust"
  REDIS_URL: "redis://redis-service.wanderlust.svc.cluster.local:6379"
